name: Databricks Connectivity & Txn Gen

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOSTNAME: ${{ secrets.DATABRICKS_HOSTNAME }}
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      AIVEN_KAFKA_BOOTSTRAP_SERVER: ${{ secrets.AIVEN_KAFKA_BOOTSTRAP_SERVER }}
      AIVEN_KAFKA_USERNAME: ${{ secrets.AIVEN_KAFKA_USERNAME }}
      AIVEN_KAFKA_PASSWORD: ${{ secrets.AIVEN_KAFKA_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Packages
        run: |
          pip install databricks-sql-connector
          pip install python-dotenv
          pip install kafka-python

      - name: Create Kafka CA Certificate
        run: |
          cat <<'EOF' > ca.pem
          ${{ secrets.AIVEN_CA_CERT }}
          EOF

      - name: Run Transaction Generator
        run: |
          python transactiongenerator.py